### ISSUE TITLE
Issues found during manual testing of 0.8.0 at deRSE24

### ISSUE THREAD

**Issue by poikilotherm** [softwarepub/hermes#244]
- [x] No log output?
- [x] No complaints about invalid CFF file -> Logs are not enabled by default, missing init to ERR/WARN/INFO.
- [x] No complaints about non-existent or missing configuration options (example: harvest.cff.validate -> harvest.cff.enable_validation & harvest.from -> harvest.sources renamed) (Potential duplication of above)
- [x] #259
- [x] #260

**Comment by poikilotherm** [comment]
Version given as `1.0` in CFF is interpreted as floating point and will give an error at deposit because not a valid string. We need to do a hard cast to string for the version

**Comment by led02** [comment]
Logs and errors are now handled a bit saner... i.e., the errors are output to the log.error channel (which is by default printed on the console).

Still lot's of stuff to do that will be handled in different issues (i.e., #238).

**Comment by sdruskat** [comment]
During the workshop, it was also mentioned that `hermes` should support older Python versions (i.e., 3.8).

I'm strictly against this, seeing that [EOLs are approaching fast](https://devguide.python.org/versions/).
3.8 will be unsupported from October 2024, 3.9 October 2025.

I'd argue that requiring 3.10 is actually feasible and shouldn't be changed.

**Comment by led02** [comment]
I think it was also required to support SOMESY

**Comment by sdruskat** [comment]
> I think 3.8 was also required to support SOMESY

True. I suggest asking somesy to update to 3.10 instead of supporting versions near the EOL. Or were there any (dependency-related) reasons for sticking with 3.8 (other than: a lot of people still use it)?

**Comment by poikilotherm** [comment]
I think we can close this issue. Python 3.8 is EOL now and even 3.10 is going to be EOL in 1 year. See also https://endoflife.date/python

The logging stuff is tracked via #138, too.

The casting stuff is tracked via #281 / #291 .
