### ISSUE TITLE
Cannot extract metadata in CI environment 

### ISSUE THREAD

**Issue by Aidajafarbigloo** [softwarepub/hermes#258]
Hello,

Although every step in the guide for using HERMES in a CI environment (https://docs.software-metadata.pub/en/latest/tutorials/automated-publication-with-ci.html) has been followed, no metadata is being extracted into the `.hermes/curate` directory in `hermes.json`. The branch is being created, but no metadata is displayed there, the only output is:

<img width="253" alt="image" src="https://github.com/hermes-hmc/hermes/assets/143706305/a2598bc2-8405-4a64-8981-766c272a987e">

Is there any step missing? Thank you for your guidance on this issue.

**Comment by led02** [comment]
Investigation showed that the CITATION.cff was not valid and hence the data was not harvested.

This especially drew a spot light on the hermes output already documented in #138, #204, #238
