### ISSUE TITLE
Yaml changes version string to integer/float -> deposit error

### ISSUE THREAD

**Issue by SKernchen** [softwarepub/hermes#281]
At the HZDR Day we had a bug doing the deposit step. In the Cff the Version is given as an integer/float (from cff init). However in the deposit step the error occurs that 
`{"status": 400, "message": "A validation error occurred.", "errors": [{"field": "metadata.version", "messages": ["Not a valid string."]}]}
`.
It was solvable by putting the version in quotation marks.
Is that maybe changed in the newer cff version?
Should we make a workaround by changing the type in the harvest step?

**Comment by zyzzyxdonta** [comment]
As far as I can tell, the `version` field in CITATION.cff is a string. But it is only parsed as a string by the yaml library if it has two dots in it, e.g. `0.1.0`. If it has only one, it is parsed as a floating point number and without a dot as an integer.

We should update our examples and tutorials to correctly quote strings in the yaml files. There's probably a linter that can help with that. On the hermes side, I think adding an extra conversion to string won't hurt.
